/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-10-05 05:33:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import work.model.dto.FlightDto;
import java.util.ArrayList;

public final class Reservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.model.dto.FlightDto");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<link type = \"text/css\" rel = \"stylesheet\" href = \"css/MainStyle.css\">\r\n");
      out.write("<title>시간표 조회</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var nation1 = new Array(\"==선택==\");\r\n");
      out.write("var vnation1 = new Array(\"\");\r\n");
      out.write("var nation2 = new Array(\"서울/김포\",\"인천\", \"청주\", \"제주\");\r\n");
      out.write("var vnation2 = new Array(\"GMP\", \"ICN\", \"CNU\",\"JJU\");\r\n");
      out.write("var nation3 = new Array(\"도쿄\",\"삿포로\", \"후쿠오카\",\"오키나와\");\r\n");
      out.write("var vnation3 = new Array(\"TKO\", \"SPR\", \"HKO\", \"OKN\");\r\n");
      out.write("var nation4 = new Array(\"베이징\",\"상하이\", \"광저우\", \"계림\");\r\n");
      out.write("var vnation4 = new Array(\"BEI\", \"SHA\", \"GUG\",\"GER\");\r\n");
      out.write("var nation5 = new Array(\"뉴욕\",\"LA\", \"텍사스\", \"플로리다\");\r\n");
      out.write("var vnation5 = new Array(\"NYK\", \"LAG\", \"TEX\",\"FRI\");\r\n");
      out.write("var nation6 = new Array(\"로마\",\"밀라노\", \"피렌체\", \"베니스\");\r\n");
      out.write("var vnation6 = new Array(\"ROM\", \"MIL\", \"FIO\", \"VEN\");\r\n");
      out.write("\r\n");
      out.write("function selectList(name, convey, value) {\r\n");
      out.write("   for(i=document.getElementById(convey).length-1; i>=0; i--){\r\n");
      out.write("      document.getElementById(convey).options[i] = null;\r\n");
      out.write("   }\r\n");
      out.write("   switch(value){\r\n");
      out.write("   case \"KOR\":\r\n");
      out.write("      for (k=0; k<nation2.length; k++) {\r\n");
      out.write("         document.getElementById(convey).options[k] = new Option(nation2[k],vnation2[k]);\r\n");
      out.write("      }\r\n");
      out.write("      break;\r\n");
      out.write("   case \"JPN\":\r\n");
      out.write("      for (k=0; k<nation3.length; k++) {\r\n");
      out.write("         document.getElementById(convey).options[k] = new Option(nation3[k],vnation3[k]);\r\n");
      out.write("      }\r\n");
      out.write("      break;\r\n");
      out.write("   case \"CHI\":\r\n");
      out.write("      for (k=0; k<nation4.length; k++) {\r\n");
      out.write("         document.getElementById(convey).options[k] = new Option(nation4[k],vnation4[k]);\r\n");
      out.write("      }\r\n");
      out.write("      break;\r\n");
      out.write("   case \"USA\":\r\n");
      out.write("      for (k=0; k<nation5.length; k++) {\r\n");
      out.write("         document.getElementById(convey).options[k] = new Option(nation5[k],vnation5[k]);\r\n");
      out.write("      }\r\n");
      out.write("      break;\r\n");
      out.write("   case \"ITA\":\r\n");
      out.write("      for (k=0; k<nation6.length; k++) {\r\n");
      out.write("         document.getElementById(convey).options[k] = new Option(nation6[k],vnation6[k]);\r\n");
      out.write("      }\r\n");
      out.write("      break;\r\n");
      out.write("   default:\r\n");
      out.write("      for (k=0; k<nation1.length; k++) {\r\n");
      out.write("         document.getElementById(convey).options[k] = new Option(nation1[k],vnation1[k]);\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("function ticket(){\r\n");
      out.write("   var obj1 = document.getElementById(\"two\");\r\n");
      out.write("   var choose = document.ReserForm.fly.value;\r\n");
      out.write("   if (choose == \"1\"){\r\n");
      out.write("      obj1.style.display = \"none\";\r\n");
      out.write("      document.ReserForm.btn_sub.style.width = \"120px\";\r\n");
      out.write("      document.ReserForm.btn_sub.style.height = \"30px\";\r\n");
      out.write("   } else {\r\n");
      out.write("      obj1.style.display = \"\";\r\n");
      out.write("      document.ReserForm.btn_sub.style.width = \"120px\";\r\n");
      out.write("      document.ReserForm.btn_sub.style.height = \"70px\";\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("function selected(){\r\n");
      out.write("   document.ReserForm.action.value = \"a_flight\";\r\n");
      out.write("   document.ReserForm.radio.value = document.ReserForm.fly.value;\r\n");
      out.write("   document.ReserForm.submit();\r\n");
      out.write("}\r\n");
      out.write("function buy(){\r\n");
      out.write("   document.ReserForm.fly.value;\r\n");
      out.write("   document.ReserForm.\r\n");
      out.write("   document.ReserForm.action = 'Seatchoice.jsp';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div align=\"right\">\r\n");
      out.write("\t");
 if (session.getAttribute("userId") != null){ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.print( session.getAttribute("userId") );
      out.write("<span>님 환영합니다.</span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/MemberController?action=m_logout\">로그아웃</a>\r\n");
      out.write("\t");
 }else{
      out.write("\r\n");
      out.write("\t<a href=\"Login.jsp\">로그인</a>\r\n");
      out.write("\t");
 }
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<table width=\"90%\">\r\n");
      out.write("\t\t<tr style=\"font-size:22px; font-family:verdana,Courier,Monospace; text-decoration: none; width:150px;\">\r\n");
      out.write("\t\t\t<td><a href=\"UserMain.jsp\"><img src=\"images/LOGO.jpg\" width=\"250px\" height=\"80px\"></a></td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#ffcc33\" width=\"180px\" height=\"80px\" align=\"center\"><a href = \"Reservation.jsp\">예매</a></td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#ffcc33\" width=\"180px\" height=\"80px\" align=\"center\"><a href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/BoardController?action=b_list\">내가 쓴 게시판</a></td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#ffcc33\" width=\"180px\" height=\"80px\" align=\"center\"><a href = \"MainController?action=noticemain\">공지사항</a></td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#ffcc33\" width=\"180px\" height=\"80px\" align=\"center\"><a href = \"javascript:modiInfor()\">개인정보 조회</a></td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#ffcc33\" width=\"180px\" height=\"80px\" align=\"center\"><a href = \"javascript:modiPass()\">PW 변경</a></td>\r\n");
      out.write("\t\t\t<td bgcolor=\"#ffcc33\" width=\"180px\" height=\"80px\" align=\"center\"><a href = \"Index.jsp\">관계자 Page</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("<form name=\"ReserForm\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AirController\">\r\n");
      out.write("<h3>\r\n");
      out.write("   ");
 
      String fly = "a";
      if (request.getAttribute("radioch") != null) {
         fly = (String)request.getAttribute("radioch");
      }
      if(fly.equals("2")) {
         out.println("<input type='radio' name='fly' value='1' onchange='ticket()'>편도");
         out.println("<input type='radio' name='fly' value='2' checked onchange='ticket()'>왕복");
      } else {
         out.println("<input type='radio' name='fly' value='1' checked onchange='ticket()'>편도");
         out.println("<input type='radio' name='fly' value='2' onchange='ticket()'>왕복");
      }
       
      out.write("\r\n");
      out.write("</h3>\r\n");
      out.write("<table align=\"center\" width=\"50%\" border=\"1\">\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td colspan=\"2\" align=\"center\">출발지</td>\r\n");
      out.write("      <td colspan=\"2\" align=\"center\">도착지</td>\r\n");
      out.write("      <td></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td align=\"center\">\r\n");
      out.write("         <select id=\"leave_nation1\" name=\"leave_nation1\" onchange=\"selectList(this.name, 'leave_city1', this.value)\">\r\n");
      out.write("            <option value=\"\">==선택==</option>\r\n");
      out.write("            <option value=\"KOR\">대한민국</option>\r\n");
      out.write("            <option value=\"JPN\">일본</option>\r\n");
      out.write("            <option value=\"CHI\">중국</option>\r\n");
      out.write("            <option value=\"USA\">미국</option>\r\n");
      out.write("            <option value=\"ITA\">이탈리아</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td align=\"center\">\r\n");
      out.write("         <select id=\"leave_city1\" name=\"leave_city1\">\r\n");
      out.write("            <option value=\"\">==선택==</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td align=\"center\">\r\n");
      out.write("         <select id=\"arrive_nation1\" name=\"arrive_nation1\" onchange=\"selectList(this.name, 'arrive_city1', this.value)\">\r\n");
      out.write("            <option value=\"\">==선택==</option>\r\n");
      out.write("            <option value=\"KOR\">대한민국</option>\r\n");
      out.write("            <option value=\"JPN\">일본</option>\r\n");
      out.write("            <option value=\"CHI\">중국</option>\r\n");
      out.write("            <option value=\"USA\">미국</option>\r\n");
      out.write("            <option value=\"ITA\">이탈리아</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td align=\"center\">\r\n");
      out.write("         <select id=\"arrive_city1\" name=\"arrive_city1\">\r\n");
      out.write("            <option value=\"\">==선택==</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td rowspan=\"2\" align=\"center\">\r\n");
      out.write("         <input type=\"hidden\" name=\"radio\">\r\n");
      out.write("         <input type=\"hidden\" name=\"action\" value=\"a_flight\">\r\n");
      out.write("         <input type=\"button\" align=\"middle\" name=\"btn_sub\" value=\"선택\" onclick=\"selected()\" style=\"width: 120px; height: 30px\">\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   ");
 if(fly.equals("2")) { 
      out.write("\r\n");
      out.write("   <tr id=\"two\">\r\n");
      out.write("   ");
 } else { 
      out.write("\r\n");
      out.write("   <tr id=\"two\" style=\"display: none;\">\r\n");
      out.write("   ");
 } 
      out.write("\r\n");
      out.write("      <td align=\"center\">\r\n");
      out.write("         <select id=\"leave_nation2\" name=\"leave_nation2\" onchange=\"selectList(this.name, 'leave_city2', this.value)\">\r\n");
      out.write("            <option value=\"\">==선택==</option>\r\n");
      out.write("            <option value=\"KOR\">대한민국</option>\r\n");
      out.write("            <option value=\"JPN\">일본</option>\r\n");
      out.write("            <option value=\"CHI\">중국</option>\r\n");
      out.write("            <option value=\"USA\">미국</option>\r\n");
      out.write("            <option value=\"ITA\">이탈리아</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td align=\"center\">\r\n");
      out.write("         <select id=\"leave_city2\" name=\"leave_city2\">\r\n");
      out.write("            <option value=\"\">==선택==</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td align=\"center\">\r\n");
      out.write("         <select id=\"arrive_nation2\" name=\"arrive_nation2\" onchange=\"selectList(this.name, 'arrive_city2', this.value)\">\r\n");
      out.write("            <option value=\"\">==선택==</option>\r\n");
      out.write("            <option value=\"KOR\">대한민국</option>\r\n");
      out.write("            <option value=\"JPN\">일본</option>\r\n");
      out.write("            <option value=\"CHI\">중국</option>\r\n");
      out.write("            <option value=\"USA\">미국</option>\r\n");
      out.write("            <option value=\"ITA\">이탈리아</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("      <td align=\"center\">\r\n");
      out.write("         <select id=\"arrive_city2\" name=\"arrive_city2\">\r\n");
      out.write("            <option value=\"\">==선택==</option>\r\n");
      out.write("         </select>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<br><br>\r\n");

if (request.getAttribute("list1") != null){
   ArrayList<FlightDto> list1 = (ArrayList<FlightDto>)request.getAttribute("list1");

      out.write("\r\n");
      out.write("<p align=\"center\">\r\n");
      out.write("   <input type=\"button\" value=\"항공권 구매\" style=\"width: 120px; height: 80px\" onclick=\"buy()\">\r\n");
      out.write("</p>\r\n");
      out.write("<br>\r\n");
      out.write("<table border=\"1\" align=\"center\" width=\"80%\">\r\n");
      out.write("   <tr>\r\n");
      out.write("      <th></th>\r\n");
      out.write("      <th width=\"13%\">날짜</th>\r\n");
      out.write("      <th width=\"10%\">고유번호</th>\r\n");
      out.write("      <th width=\"10%\">편명</th>\r\n");
      out.write("      <th width=\"13%\">출발지</th>\r\n");
      out.write("      <th width=\"15%\">출발시각</th>\r\n");
      out.write("      <th width=\"13%\">도착지</th>\r\n");
      out.write("      <th width=\"15%\">도착시각</th>\r\n");
      out.write("      <th width=\"*%\">게이트</th>\r\n");
      out.write("   </tr>\r\n");
      out.write("   ");
 if(list1.isEmpty()){ 
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"9\" align=\"center\">등록된 일정이 없습니다.</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("   ");
   } else {
      for(int i=0; i<list1.size(); i++){
         FlightDto dto = list1.get(i);
   
      out.write("\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td align=\"center\"><input type=\"radio\" name=\"start\" value=\"\"></td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfDate() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfANum() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfFName() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfLeave() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfLeaveDate() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfArrive() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfArriveDate() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfGate() );
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   ");
 } } 
      out.write("\r\n");
      out.write("</table>\r\n");
 } 
      out.write("\r\n");
      out.write("<br><br><br>\r\n");

if (request.getAttribute("list2") != null){
   ArrayList<FlightDto> list2 = (ArrayList<FlightDto>)request.getAttribute("list2");

      out.write("\r\n");
      out.write("<table border=\"1\" align=\"center\" width=\"80%\">\r\n");
      out.write("   <tr>\r\n");
      out.write("      <th></th>\r\n");
      out.write("      <th width=\"13%\">날짜</th>\r\n");
      out.write("      <th width=\"10%\">고유번호</th>\r\n");
      out.write("      <th width=\"10%\">편명</th>\r\n");
      out.write("      <th width=\"13%\">출발지</th>\r\n");
      out.write("      <th width=\"15%\">출발시각</th>\r\n");
      out.write("      <th width=\"13%\">도착지</th>\r\n");
      out.write("      <th width=\"15%\">도착시각</th>\r\n");
      out.write("      <th width=\"*%\">게이트</th>\r\n");
      out.write("   </tr>\r\n");
      out.write("   ");
 if(list2.isEmpty()){ 
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"9\" align=\"center\">등록된 일정이 없습니다.</td>\r\n");
      out.write("         </tr>\r\n");
      out.write("   ");
   } else {
      for(int i=0; i<list2.size(); i++){
         FlightDto dto = list2.get(i);
   
      out.write("\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td align=\"center\"><input type=\"radio\" name=\"end\"></td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfDate() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfANum() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfFName() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfLeave() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfLeaveDate() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfArrive() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfArriveDate() );
      out.write("</td>\r\n");
      out.write("      <td align=\"center\">");
      out.print( dto.getfGate() );
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   ");
 } } 
      out.write("\r\n");
      out.write("</table>\r\n");
 } 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
